### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by moshechen** [Mindinventory/python-stock-prediction#1]
Hi,

I have been getting this error when running the code on Jupiter notebook:

When it gets to this part of the code:
X_train =X_train.reshape(X_train.shape[0],X_train.shape[1] , 1)
X_test = X_test.reshape(X_test.shape[0],X_test.shape[1] , 1)

I am getting the following error: 
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_10524/2467880729.py in <module>
      1 X_train =X_train.reshape(X_train.shape[0],X_train.shape[1] , 1)
----> 2 X_test = X_test.reshape(X_test.shape[0],X_test.shape[1] , 1)

IndexError: tuple index out of range

Any idea what is happening? 

Thank You 

Moshe

[AAPL.csv](https://github.com/Mindinventory/python-stock-prediction/files/7782323/AAPL.csv)

**Comment by kp-nagar** [comment]
Hi Moshe,
I checked your data file. So here is a note for you. I also mention this into my blog you can check here
"https://medium.com/mindful-engineering/stock-price-prediction-using-artificial-recurrent-neural-network-part-1-5955f93b6734?source=friends_link&sk=a9e18dcd07b895b2481ff89ab1114555" 

Note: Please check data (in this case AAPL.csv) size using df.info. its size must be more than 3000 entries.
If data(in this case AAPL.csv) is less than 3000 then you have to change time_step size less than 100 like (30,40,or 50) in program as show in figure K.

thank you
Kumar

**Comment by moshechen** [comment]
Thank you very much Kumar. Much appreciated. 

Also, your blog is fantastic and I learned a lot from it. Thank you for putting it together. 
 
Thank you :-) 

Moshe
